services:
  postgres:
    image: 'postgres:latest'
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=D@vitanje123
      - POSTGRES_USER=postgres
    ports:
      - '5432:5432'
