INSERT INTO Product (name, description, price, available_quantity)
VALUES
    ('Milk', 'A nutritious dairy product that is rich in calcium and essential vitamins.', 2.99, 100),
    ('Bread', 'Freshly baked bread with a crispy crust and soft interior.', 1.99, 150),
    ('Apples', 'Crisp and juicy apples harvested from local orchards.', 0.99, 200),
    ('Eggs', 'Farm-fresh eggs with golden yolks.', 3.49, 120),
    ('Chicken Breast', 'Lean and tender chicken breast.', 5.99, 80),
    ('Rice', 'High-quality long-grain rice.', 4.99, 250),
    ('Pasta', 'Al dente pasta made from premium durum wheat.', 2.49, 300),
    ('Tomatoes', 'Plump and ripe tomatoes bursting with flavor.', 1.29, 180),
    ('Cheese', 'A selection of gourmet cheeses, crafted with care.', 6.99, 90),
    ('Yogurt', 'Creamy and probiotic-rich yogurt.', 1.79, 150),
    ('Spinach', 'Fresh and vibrant spinach leaves.', 1.99, 220),
    ('Salmon', 'Premium salmon fillets.', 9.99, 70),
    ('Ground Beef', 'High-quality ground beef.', 7.99, 100),
    ('Bananas', 'Naturally sweet bananas.', 0.59, 135),
    ('Carrots', 'Crisp and nutritious carrots.', 0.89, 160),
    ('Orange Juice', 'Freshly squeezed orange juice.', 3.49, 210),
    ('Cucumber', 'Refreshing and hydrating cucumbers.', 0.99, 45),
    ('Avocado', 'Creamy and nutritious avocados.', 2.99, 67),
    ('Ground Coffee', 'Aromatic and rich ground coffee.', 8.99, 56),
    ('Green Tea', 'High-quality green tea leaves.', 3.99, 345),
    ('Peanut Butter', 'Smooth and creamy peanut butter.', 4.49, 456),
    ('Honey', 'Pure and natural honey.', 5.99, 70),
    ('Oatmeal', 'Nutritious and hearty oatmeal.', 2.99, 237),
    ('Greek Yogurt', 'Thick and tangy Greek yogurt.', 1.99, 432),
    ('Lemons', 'Tangy and refreshing lemons.', 0.79, 312),
    ('Broccoli', 'Nutrient-rich broccoli florets.', 2.49, 230),
    ('Olive Oil', 'Extra virgin olive oil.', 9.99, 164),
    ('Almonds', 'Crunchy and nutritious almonds.', 4.99, 65),
    ('Quinoa', 'Protein-packed quinoa seeds.', 3.99, 64),
    ('Dark Chocolate', 'Rich and indulgent dark chocolate.', 2.49, 45);
