ALTER TABLE orderitem ALTER COLUMN product_id TYPE BIGINT;

ALTER TABLE product ALTER COLUMN id TYPE BIGINT;

ALTER TABLE orderitem ALTER COLUMN order_id TYPE BIGINT;

ALTER TABLE Orders ALTER COLUMN id TYPE BIGINT;

ALTER TABLE users ALTER COLUMN id TYPE BIGINT;

